language: java
dist: bionic

jdk:
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_OPTS='-Xmx1024m -Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true'
    - JAVA_OPTS='-Xmx1024m'

jobs:
  include:
    - stage: test
      install:
        - alias build="go run tools/monorepo/monorepo.go"
      name: test changed modules
      if: type == pull_request
      script:
        - build -path=services/server -command="./gradlew -p services/server test"  -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=services/client -command="./gradlew -p services/client test"  -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=libraries/logging -command="./gradlew -p libraries/logging test"  -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=libraries/common -command="./gradlew -p libraries/common test"  -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=tools/gradle-plugins/gradle-hello-plugin -command="./gradlew -p tools/gradle-plugins/gradle-hello-plugin test"  -commitRange=$TRAVIS_COMMIT_RANGE

    - stage: build
      install:
        - alias build="go run tools/monorepo/monorepo.go"
      name: build changed modules
      if: type != pull_request
      script:
        - build -path=services/server -command="./gradlew -p services/server assemble" -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=services/client -command="./gradlew -p services/client assemble" -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=libraries/logging -command="./gradlew -p libraries/logging assemble" -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=libraries/common -command="./gradlew -p libraries/common assemble" -commitRange=$TRAVIS_COMMIT_RANGE
        - build -path=tools/gradle-plugins/gradle-hello-plugin -command="./gradlew -p tools/gradle-plugins/gradle-hello-plugin assemble" -commitRange=$TRAVIS_COMMIT_RANGE
